//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KursovayaRabotaIsp4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип фото.
    /// </summary>
    // *** Start programmer edit section *** (ТипФото CustomAttributes)

    // *** End programmer edit section *** (ТипФото CustomAttributes)
    [AutoAltered()]
    [Caption("Тип фото")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТипФотоE", new string[] {
            "Код as \'Код\'",
            "Вид as \'Вид\'",
            "Стоимость as \'Стоимость\'"})]
    [View("ТипФотоL", new string[] {
            "Код as \'Код\'",
            "Вид as \'Вид\'",
            "Стоимость as \'Стоимость\'"})]
    public class ТипФото : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private IIS.KursovayaRabotaIsp4.ВыборВида fВид;
        
        private int fСтоимость;
        
        // *** Start programmer edit section *** (ТипФото CustomMembers)

        // *** End programmer edit section *** (ТипФото CustomMembers)

        
        /// <summary>
        /// Вид.
        /// </summary>
        // *** Start programmer edit section *** (ТипФото.Вид CustomAttributes)

        // *** End programmer edit section *** (ТипФото.Вид CustomAttributes)
        public virtual IIS.KursovayaRabotaIsp4.ВыборВида Вид
        {
            get
            {
                // *** Start programmer edit section *** (ТипФото.Вид Get start)

                // *** End programmer edit section *** (ТипФото.Вид Get start)
                IIS.KursovayaRabotaIsp4.ВыборВида result = this.fВид;
                // *** Start programmer edit section *** (ТипФото.Вид Get end)

                // *** End programmer edit section *** (ТипФото.Вид Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТипФото.Вид Set start)

                // *** End programmer edit section *** (ТипФото.Вид Set start)
                this.fВид = value;
                // *** Start programmer edit section *** (ТипФото.Вид Set end)

                // *** End programmer edit section *** (ТипФото.Вид Set end)
            }
        }
        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (ТипФото.Код CustomAttributes)

        // *** End programmer edit section *** (ТипФото.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (ТипФото.Код Get start)

                // *** End programmer edit section *** (ТипФото.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (ТипФото.Код Get end)

                // *** End programmer edit section *** (ТипФото.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТипФото.Код Set start)

                // *** End programmer edit section *** (ТипФото.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (ТипФото.Код Set end)

                // *** End programmer edit section *** (ТипФото.Код Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (ТипФото.Стоимость CustomAttributes)

        // *** End programmer edit section *** (ТипФото.Стоимость CustomAttributes)
        public virtual int Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (ТипФото.Стоимость Get start)

                // *** End programmer edit section *** (ТипФото.Стоимость Get start)
                int result = this.fСтоимость;
                // *** Start programmer edit section *** (ТипФото.Стоимость Get end)

                // *** End programmer edit section *** (ТипФото.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТипФото.Стоимость Set start)

                // *** End programmer edit section *** (ТипФото.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (ТипФото.Стоимость Set end)

                // *** End programmer edit section *** (ТипФото.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТипФотоE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТипФотоE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТипФотоE", typeof(IIS.KursovayaRabotaIsp4.ТипФото));
                }
            }
            
            /// <summary>
            /// "ТипФотоL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТипФотоL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТипФотоL", typeof(IIS.KursovayaRabotaIsp4.ТипФото));
                }
            }
        }
    }
}
